# Generated by Django 2.2.13 on 2021-08-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is an description of this picture'),
            preserve_default=False,
        ),
    ]
